data:extend({
  {
    type = "double-setting",
    name = "bertorio-drop-chance-mat1",
    setting_type = "runtime-global",
    default_value = 0.04,
    minimum_value = 0,
    maximum_value = 1,
    order = "a",
  },
  {
    type = "double-setting",
    name = "bertorio-drop-chance-mat2",
    setting_type = "runtime-global",
    default_value = 0.01,
    minimum_value = 0,
    maximum_value = 1,
    order = "b",
  },
  {
    type = "double-setting",
    name = "bertorio-speed-mk1",
    setting_type = "runtime-global",
    default_value = 1.0,
    minimum_value = 0,
    order = "c",
  },
  {
    type = "double-setting",
    name = "bertorio-speed-mk2",
    setting_type = "runtime-global",
    default_value = 2.0,
    minimum_value = 0,
    order = "d",
  },
  {
    type = "double-setting",
    name = "bertorio-speed-mk3",
    setting_type = "runtime-global",
    default_value = 3.0,
    minimum_value = 0,
    order = "e",
  },
  {
    type = "bool-setting",
    name = "bertorio-pity-enabled",
    setting_type = "runtime-global",
    default_value = true,
    order = "f",
  },
  {
    type = "bool-setting",
    name = "bertorio-stats-enabled",
    setting_type = "runtime-global",
    default_value = false,
    order = "g",
  },
})
